sw_soap_comment:
    resource: "@SwSoapCommentBundle/Resources/config/routing.yml"
    prefix:   /soap/

_besimple_soap:
    resource: "@BeSimpleSoapBundle/Resources/config/routing/webservicecontroller.xml"
    prefix:   /ws
